function rf_distalness_table = getRFDistalnessTable()
% Function to get a table of all colors corresponding to a receptive field

% receptive field colors from color brewer (sequential)
rf_distalness = {...
    'arm',NaN;...
    'torso',1;...
    'shoulder',2;...
    'humerus',3;...
    'elbow',4;...
    'forearm',5;...
    'wrist',6;...
    'hand',7};
rf_distalness_table = cell2table(rf_distalness,'VariableNames',{'receptive_field','rf_distalness'});
